include /etc/nginx/modules-enabled/50-mod-http-brotli-filter.conf;

worker_processes auto;
worker_rlimit_nofile 65535;
user USERNAME;
pid /run/nginx.pid;

events {
	worker_connections 4096;
}

http {
	include mime.types;
	default_type application/octet-stream;
	access_log /path/to/log/access.log;
	error_log  /path/to/log/error.log warn;
	sendfile on;

	server {
		server_name www.vdb.im;
		return 301 https://vdb.im$request_uri;
	}

	server {
 		listen 443 ssl; # managed by Certbot
		server_name vdb.im;
		ssl_certificate /etc/letsencrypt/live/vdb.im/fullchain.pem; # managed by Certbot
		ssl_certificate_key /etc/letsencrypt/live/vdb.im/privkey.pem; # managed by Certbot
		include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
		ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

		brotli on;
		brotli_types text/html text/css application/json application/javascript image/svg+xml;

		gzip on;
		gzip_types text/html text/css application/json application/javascript image/svg+xml;

		root /home/terran/vdb/frontend/dist;
		index index.html;

		location /index.html {
			add_header Cache-Control "no-cache";
		}

		location / {
			add_header Cache-Control "public, max-age=31536000, immutable";
			try_files $uri $uri/ /index.html;
		}


		location /images/ {
			add_header Cache-Control "public, max-age=31536000, immutable";
		}

		location /api {
			proxy_pass http://localhost:5001/api;
		}
	}

	server {
	    listen 80 default_server;
	    server_name _;
	    return 301 https://$host$request_uri;
	}
}
