const artists = [
  'Aaron Acevedo',
  'Aaron Voss',
  'Abrar Ajmal',
  'Alan Rabinowitz',
  'Alan Rabinowitz; Brian LeBlanc',
  'Alan Rabinowitz; Ken Meyer, Jr.',
  'Alan Rabinowitz; Melissa Uran',
  'Albrecht',
  'Alejandro Collucci',
  'Alejandro Collucci; Jeff Menges',
  'Alejandro Collucci; Kaja Foglio',
  'Alejandro Colucci',
  'Alejandro F. Giraldo',
  'Alexander Dunnigan',
  'Amy Weber',
  'Amy Weber; Hannibal King; Brian LeBlanc',
  'Amy Weber; Mark Nelson',
  'Amy Weber; Michael Astrachan',
  'Amy Weber; Phillip Tan; Bob Stevlic',
  'Andre Freitas',
  'Andre Gates',
  'Andrew Bates',
  'Andrew Bates; Mike Chaney; Andrew Bates',
  'Andrew Hepworth',
  'Andrew Robinson',
  'Andrew Trabbold',
  'Andrew Trabbold; Anson Maddocks',
  'Andrew Trabbold; Jeff Menges',
  'Andrew Trabbold; Ken Meyer, Jr.',
  'Andrew Trabbold; Michael Weaver',
  'Anna Evertsdotter',
  'Anna Evertsdotter; Gines Quinonero',
  'Anson Maddocks',
  'Anson Maddocks; Anna Christenson',
  'Anson Maddocks; Ash Arnett; Arkady Roytman',
  'Anson Maddocks; Brad Williams',
  'Anson Maddocks; Dave Seeley',
  'Anson Maddocks; Hannibal King',
  'Anson Maddocks; Jeff Holt',
  'Anson Maddocks; Lawrence Snelly',
  'Anson Maddocks; Mike Danza',
  'Anson Maddocks; Sam Araya',
  'Ari Targownik',
  'Arthur Roberg',
  'Ash Arnett',
  'Attila Adorjany',
  'Attila Adorjany; Eric Kim',
  'August B\u00f8gedal Hansen',
  'Avery Butterworth',
  'Becky Cloonan',
  'Becky Jollensten',
  'Ben Mirabelli',
  'Beth Trott',
  'Brad Williams',
  'Brian Ashmore',
  'Brian Horton',
  'Brian LeBlanc',
  'Brian LeBlanc; Francesc Grimalt; Brian LeBlanc',
  'Brian LeBlanc; Gines Quinonero; Brian LeBlanc',
  'Brian LeBlanc; Kaja Foglio',
  'Brian LeBlanc; L. A. Williams',
  'Brian LeBlanc; Margaret Organ-Kean',
  'Brian LeBlanc; Mike Raabe',
  'Brian LeBlanc; Rob Alexander',
  'Brian LeBlanc; Robert McNeill',
  'Brian LeBlanc; Steve Ellis',
  'Brian Miskelley',
  'Brian Snoddy',
  'Brian Snoddy; Darryl Elliott',
  'Brian Snoddy; Joel Biske',
  'Brian Snoddy; Roger Raupp; Gary Chatterton; Roger Raupp',
  'Brian Snoddy; Ron Spencer',
  'Bryon Wackwitz',
  'Bryon Wackwitz; Gary Chatterton',
  'Caleb Cleaveland',
  'Carmen Cornet',
  'Chad Michael Ward',
  'Chet Masters',
  'Chet Masters; Mike Chaney',
  'Chet Masterz',
  'Chris McLoughlin',
  'Chris McLoughlin; Bob Stevlic',
  'Chris McLoughlin; Kieran Yanner',
  'Chris Richards',
  'Chris Stevens',
  'Chris Stevens; Bryon Wackwitz',
  'Chris Stevens; Richard Thomas',
  'Christel Espenkrona',
  'Christel Espenkrona; Ken Meyer, Jr.',
  'Christopher Rush',
  'Christopher Rush; Brian LeBlanc',
  'Christopher Rush; Clint Langley',
  'Christopher Rush; Nilson',
  'Christopher Shy',
  'Cliff Nielson',
  'Clint Langley',
  'Clint Langley; L. A. Williams; Avery Butterworth',
  'Clint Langley; Scott Kirschner',
  'Corey Macourek',
  'Corey Macourek; Mark Poole',
  'Cos Koniotis',
  'Craig Grant',
  'Craig Maher',
  'Dan Frazier',
  'Dan Frazier; Chris Stevens',
  'Dan Frazier; Jeff Holt',
  'Dan Frazier; Mike Huddleston',
  'Dan Frazier; Ron Spencer',
  'Dan Smith',
  'Dan Smith; Chris Stevens',
  'Dan Smith; Fred Hooper',
  'Dan Smith; Jeff Holt',
  'Dan Smith; Joel Biske',
  'Daniel Gelon',
  'Daniel Gelon; Dave Seeley',
  'Daniel Gelon; John Bridges',
  'Daniel Gelon; Nilson; Ken Meyer, Jr.',
  'Darryl Elliott',
  'Dave Leri',
  'Dave Leri; E.M. Gist',
  'Dave Roach',
  'Dave Roach & Pete Burges',
  'Dave Roach & Pete Burges & John Kent',
  'Dave Roach & Pete Burges; Brian LeBlanc',
  'Dave Roach & Pete Burges; Chris Stevens; Dave Roach & Pete Burges',
  'Dave Roach & Pete Burges; Mark Nelson',
  'Dave Roach; John Kent',
  'Dave Roach; Pete Burges',
  'Dave Roach; Pete Burges; Avery Butterworth',
  'Dave Roach; Steve Ellis',
  'Dave Seeley',
  'David Day',
  'David Fooden',
  'David Fooden; Steve Casper',
  'David Ho',
  'David Kimmel',
  'Dennis Calero',
  'Diana Vick',
  'Dimple',
  'Doug Alexander',
  'Doug Gregory',
  'Doug Gregory; Drew Tucker; Melissa Uran',
  'Doug Stambaugh',
  'Douglas Shuler',
  'Douglas Shuler; Andrew Trabbold',
  'Douglas Shuler; Dave Seeley',
  'Douglas Shuler; Harold Arthur McNeill; Gary Chatterton; Gines Quinonero',
  'Douglas Shuler; Mike Dringenberg; Marco Marzoni',
  'Douglas Shuler; Sue Ann Harkey',
  'Drew Tucker',
  'Drew Tucker; Brian Snoddy',
  'Drew Tucker; Jeff Holt',
  'Drew Tucker; Ken Meyer, Jr.',
  'Drew Tucker; Kieran Yanner',
  'Drew Tucker; Sandra Everingham',
  'Durwin Talon',
  'E.M. Gist',
  'EM Gist',
  'Ed Tadem',
  'Edward Beard, Jr.',
  'Edward Beard, Jr.; Brian LeBlanc',
  'Edward Beard, Jr.; James Stowe',
  'Edward Beard, Jr.; Katie McCaskill',
  'Edward Beard, Jr.; Richard Thomas',
  'Efrem Palacios',
  'Elli Adams',
  'Eric Deschamps',
  'Eric Kim & Attila Adorjany',
  'Eric LaCombe',
  'Eric LaCombe; Anna Christenson',
  'Eric LaCombe; Anson Maddocks',
  'Eric Lofgren',
  'Erica Danell',
  'Francesc Grimalt',
  'Franz Vohwinkel',
  'Fred Harper',
  'Fred Hooper',
  'Fred Hooper; Dan Smith',
  'Fred Hooper; Steve Casper',
  'Gabor Nemeth',
  'Gary Leach',
  'Gines Quinonero',
  'Gines Quinonero-Santiago',
  'Glen Osterberger',
  'Glenn Osterberger',
  'Grant Garvin',
  'Greg Boychuk',
  'Greg Loudon',
  'Greg Loudon; Jenny Frison',
  'Greg Simanson',
  'Greg Simanson; Brian LeBlanc',
  'Greg Simanson; Nicola Leonard; Peter Morbacher',
  'Grzegorz Bobrowski',
  'Hannibal King',
  'Harold Arthur McNeill',
  'Harold Arthur McNeill; Britt Martin',
  'Harold Arthur McNeill; Carmen Cornet',
  'Harold Arthur McNeill; Javier Santos',
  'Harold Arthur McNeill; Jeff Holt',
  'Harold Arthur McNeill; Jim Di Bartolo',
  'Harold Arthur McNeill; Joe Slucher',
  'Harold Arthur McNeill; John McCrea',
  'Harold Arthur McNeill; Karl Waller; Avery Butterworth',
  'Harold Arthur McNeill; Leif Jones',
  'Heather Hudson',
  'Heather Hudson; Andrew Trabbold',
  'Heather Hudson; Brian LeBlanc',
  'Heather Hudson; Dave Seeley; Ron Spencer',
  'Heather Hudson; Leif Jones',
  'Heather Hudson; Mike Huddleston',
  'Heather Hudson; Steve Ellis',
  'Heather Hudson; Steve Prescott',
  'Heather J. McKinney',
  'Heather Kreiter',
  'Heather V. Kreiter',
  'Ian Hernaiz',
  'Imaginary Friends Studios',
  'Imaginary Friends Studios; Javier Santos; Imaginary Friends Studios',
  'J Frederick Y',
  'Jake Smidt',
  'James Allen Higgins',
  'James Richardson',
  'James Stowe',
  'James Stowe; Javier Santos; James Stowe',
  'James Stowe; Richard Thomas',
  'Jami Waggoner',
  'Jared Smith',
  'Jarkko Suvela',
  'Jason Alexander Behnke',
  'Jason Alexander Behnke; Britt Martin',
  'Jason Brubaker',
  'Javier Santos',
  'Jeff "el jefe" Holt',
  'Jeff Holt',
  'Jeff Holt; L. A. Williams',
  'Jeff Holt; Margaret Organ-Kean',
  'Jeff Holt; Ne Ne Thomas',
  'Jeff Klimek',
  'Jeff Laubenstein',
  'Jeff Menges',
  'Jeff Menges; Alejandro Collucci',
  'Jeff Menges; Brian LeBlanc',
  'Jeff Menges; Christopher Shy',
  'Jeff Menges; Eric Lofgren',
  'Jeff Menges; Leif Jones',
  'Jeff Miracola',
  'Jeff Rebner',
  'Jeff Rebner; Peter Kim',
  'Jenny Frison',
  'Jeremy C. Bills',
  'Jeremy McHugh',
  'Jesus Ybarzabal',
  'Jim Di Bartolo',
  'Jim DiBartolo',
  'Jim Nelson',
  'Jim Nelson; Pete Burges; Dave Roach',
  'Jim Pavelec',
  'Joe Ziolkowski',
  'Joel Biske',
  'Joel Biske; Anson Maddocks',
  'Joel Biske; Susan Van Camp',
  'John Bolton',
  'John Bridges',
  'John Bridges; Hannibal King',
  'John Bridges; Lawrence Snelly',
  "John Bridges; William O'Connor",
  'John Matson',
  'John McCrea',
  'John Scotello',
  'John Scotello; Gary Chatterton',
  'John Scotello; Melissa Uran',
  'John Van Fleet',
  'Josh Timbrook',
  'Josh Timbrook; Jeff Holt',
  'Juan Antonio Serrano Garcia',
  'Juan Calle',
  'Julian Jackson',
  'Julie Collins; Jeff Menges',
  'Justin Norman',
  'Kaja Foglio',
  'Kaja Foglio; Brian LeBlanc',
  'Kaja Foglio; Durwin Talon',
  'Kaja Foglio; James Stowe',
  'Kaja Foglio; Ron Spencer',
  "Kaja Foglio; William O'Connor",
  'Kari Christensen',
  'Karl Waller',
  'Katie McCaskill',
  'Kelly Howlett',
  'Ken Meyer, Jr.',
  'Ken Meyer, Jr.; Harold Arthur McNeill',
  'Ken Meyer, Jr.; Mark Tedin',
  'Kent Williams',
  'Kevin McCann',
  'Kevin McCann; Brian LeBlanc',
  'Kieran Yanner',
  'Kieran Yanner; Mark Poole',
  "Kieran Yanner; William O'Connor",
  'Kyri Koniotis',
  'L. A. Williams',
  'L. A. Williams; Chet Masters; Mike Chaney',
  'L. A. Williams; Durwin Talon',
  'L. A. Williams; Fred Hooper',
  'L. A. Williams; Harold Arthur McNeill; Anna Christenson',
  'L. A. Williams; James Stowe',
  'L. A. Williams; Jeff Holt',
  'L. A. Williams; Julie Collins',
  'L. A. Williams; Mark Kelly',
  'L. A. Williams; Mark Tedin',
  'L. A. Williams; Randy Gallegos',
  'L. A. Williams; Randy Gallegos; John Bridges',
  'L. A. Williams; Richard Thomas',
  'L. A. Williams; Steve Prescott',
  'L. Snelly & D. Fryendall',
  'Laia Lopez Tubau',
  'Larry MacDougall',
  'Larry MacDougall; Chris Stevens',
  'Larry MacDougall; Gary Chatterton; Gines Quinonero',
  'Lawrence Snelly',
  'Lee Carter',
  'Lee Dotson',
  'Leif Jones',
  'Leif Jones; Amy Weber',
  'Leif Jones; Anson Maddocks',
  'Leif Jones; Mark Poole',
  'Liz Danforth',
  'Marco Nelor',
  'Margaret Organ-Kean',
  'Margaret Organ-Kean; Greg Simanson',
  'Margaret Organ-Kean; Richard Thomas',
  'Margaret Organ-Kean; Steve Ellis; Gines Quinonero',
  'Marian Churchland',
  'Marian Churchland; Gines Quinonero; Marian Churchland',
  'Mark Kelly',
  'Mark Nelson',
  'Mark Nelson; Anson Maddocks',
  'Mark Poole',
  'Mark Poole; Brian LeBlanc',
  'Mark Poole; Corey Macourek',
  'Mark Poole; Jarkko Suvela; Mark Poole',
  'Mark Poole; Jeff Holt',
  'Mark Poole; Oliver Meinerding',
  'Mark Tedin',
  'Mark Tedin; Brad Williams',
  'Mark Tedin; Fred Hooper',
  'Mark Tedin; Joe Ziolkowski',
  'Mark Tedin; Matt Wilson',
  'Mark Tedin; Sam Araya',
  "Mark Tedin; William O'Connor",
  'Mathias Kollros',
  'Mathias Tapia',
  'Matt Cavotta',
  'Matt Dixon',
  'Matt Mitchell',
  'Matt Smith',
  'Matt Wilson',
  'Matt Wilson; Brian Snoddy',
  'Matthew Mitchell',
  'Mattias Tapia',
  'Max Shade Fellwalker',
  'Max Shade Fellwalker; Sandra Everingham',
  'Melissa Benson',
  'Melissa Benson; Eric Lofgren',
  'Melissa Benson; Fred Hooper',
  'Melissa Benson; Peter Bergting',
  'Melissa Benson; Sandra Everingham',
  'Michael Astrachan',
  'Michael Astrachan; Eric Lofgren',
  'Michael Dixon',
  'Michael Dixon; Richard Thomas',
  'Michael Gaydos',
  'Michael Weaver',
  'Michael Weaver; Durwin Talon',
  'Michael Weaver; Kieran Yanner',
  'Michael Weaver; Melissa Uran',
  'Michael Weaver; Mike Danza',
  'Michael Weaver; Mike Huddleston',
  'Michael Weaver; Sam Araya',
  'Mick Bertilorenzi',
  'Mike Chaney',
  'Mike Danza',
  'Mike Danza; Edward Beard, Jr.',
  'Mike Dringenberg',
  'Mike Dringenberg; Douglas Shuler',
  'Mike Gaydos',
  'Mike Gaydos & Mike Chaney',
  'Mike Huddleston',
  'Mike Raabe',
  'Mike Raabe; James Stowe',
  'Mike Raabe; John Bridges',
  'Mike Raabe; Ne Ne Thomas',
  'Mike Weaver',
  'Monte Moore',
  'Ne Ne Thomas',
  'Ne Ne Thomas; Andrew Trabbold',
  'Ne Ne Thomas; Brian LeBlanc',
  'Ne Ne Thomas; Greg Simanson',
  'Ne Ne Thomas; Jim Nelson',
  'Newel Anderson',
  'Nicola Leonard',
  'Nicola Leonard; Brian LeBlanc',
  'Nicola Leonard; Chet Masters; Mike Chaney',
  'Nicolas "Dimple" Bigot',
  'Nicolas Bigot',
  'Nicole Cardiff',
  'Nigel Sade',
  'Nilson',
  'Nilson; Ne Ne Thomas',
  'Noah Hirka',
  'Noora Hirvonen',
  'Oscar Salcedo; Mark Kelly',
  'Pat Loboyko',
  'Pat McEvoy',
  'Pat Morrissey',
  'Pat Morrissey; Jeff Holt',
  'Pat Morrissey; Sam Araya',
  'Patrick Kochakji',
  'Patrick Lambert',
  'Patrick McEvoy',
  'Paul Ballard',
  'Paul Tobin',
  'Pete Burges',
  'Pete Burges & Dave Roach',
  'Pete Venters',
  'Pete Venters; Anna Christenson',
  'Pete Venters; Brian LeBlanc',
  'Pete Venters; Chris Stevens',
  'Pete Venters; Jenny Frison',
  'Pete Venters; John Bridges',
  'Pete Venters; Julie Collins',
  'Pete Venters; Mark Nelson',
  'Pete Venters; Mike Danza',
  'Pete Venters; Riccardo Fabiani',
  'Pete Venters; Sam Araya',
  'Pete Venters; Steve Prescott',
  'Peter Bergting',
  'Peter Bergting; Bryon Wackwitz',
  'Peter Bergting; Dan Frazier',
  'Peter Bergting; Lawrence Snelly',
  'Peter Kim',
  'Phil Wohr',
  'Phillip Hilliker',
  'Phillip Tan',
  'Quinton Hoover',
  'Quinton Hoover; Brian LeBlanc',
  'Quinton Hoover; Pete Venters',
  'Quinton Hoover; Steve Prescott',
  'Randy Asplund',
  'Randy Gallegos',
  'Randy Gallegos; Becky Cloonan',
  'Randy Gallegos; Paul Ballard',
  'Randy Gallegos; Ron Spencer',
  'Randy Gallegos; Ted Naifeh; Eric Deschamps',
  'Rebecca Guay',
  'Rebecca Guay; Eric Deschamps',
  'Riccardo Fabiani',
  'Richard Kane Ferguson',
  'Richard Kane Ferguson; Jim DiBartolo',
  'Richard Thomas',
  'Richard Thomas; Anson Maddocks',
  'Richard Thomas; Brian LeBlanc',
  'Richard Thomas; Greg Simanson',
  'Richard Thomas; Michael Astrachan; Jeff Holt',
  'Richard Thomas; Mike Dringenberg',
  'Richard Thomas; Ron Spencer; Ron Spenser',
  'Richard Thomas; Scott Fischer',
  'Rick Berry',
  "Rick O'Brien",
  'Rik Martin',
  'Rob Alexander',
  'Rob Alexander; Chet Masters; Mike Chaney; Gines Quinonero',
  'Robert McNeill',
  'Robert McNeill; Jim Nelson',
  'Robin Chyo',
  'Roel Wielinga',
  'Ron Lemon',
  'Ron Spencer',
  'Ron Spencer; Brad Williams',
  'Ron Spencer; Gary Chatterton',
  'Ron Spencer; Harold Arthur McNeill',
  'Ron Spencer; L. A. Williams; Oliver Meinerding',
  'Ron Spencer; Michael Astrachan; Ron Spencer',
  'Ron Spencer; Pete Venters',
  'Ron Spencer; Ron Spenser',
  'Ron Van Halen',
  'Ruben Bravo',
  'Sam Araya',
  'Samuel Araya',
  'Sandra Chang',
  'Sandra Chang-Adair',
  'Sandra Chang-Adair; Gines Quinonero; Sandra Chang-Adair',
  'Sandra Everingham',
  'Sandra Everingham; Gary Chatterton; Sandra Everingham',
  'Satyr',
  'Scott Fischer',
  'Scott Kirschner',
  'Scott Kirschner; Brian LeBlanc',
  'Scott Kirschner; Gary Chatterton',
  'Scott Kirschner; Jeff Holt',
  'Scott Kirschner; Katie McCaskill',
  'Scott M. Bakal; Brian LeBlanc',
  'Shane Coppage',
  'Steve Casper',
  'Steve Casper; Becky Jollensten',
  'Steve Eidson',
  'Steve Ellis',
  'Steve Ellis; Drew Tucker',
  'Steve Ellis; Javier Santos; Steve Ellis',
  'Steve Ellis; Robert McNeill',
  'Steve Prescott',
  'Stuart Beel',
  'Stuart Beel; Craig Grant',
  'Stuart Beel; Eric Deschamps',
  'Stuart Beel; John Bridges',
  'Stuart Beel; L. A. Williams',
  'Stuart Beel; Stuart Sayger',
  'Stuart Beel; Will Simpson',
  'Susan Van Camp',
  'Susan Van Camp; Christopher Shy',
  'Susan Van Camp; Darryl Elliott; Joe Slucher',
  'Talon Dunning',
  'Talon Dunning; Gines Quinonero',
  'Ted Naifeh',
  'Ted Naifeh; Harold Arthur McNeill',
  'Terese Nielsen',
  'Thea Maia',
  'Thea Maia; Tom Biondillo',
  'Theodore Black',
  'Thomas Baxa',
  'Thomas Denmark',
  'Thomas Manning',
  'Thomas Nairb',
  'Thomas Nairb; Christopher Rush',
  'Tim Bradstreet & Grant Goleash',
  'Tim Bradstreet & Grant Goleash; T. Bradstreet & G. Goleash',
  'Tom Baxa',
  'Tom Biondillo',
  'Tom Duncan',
  'Tom Gianni',
  'Tom Gianni; Stuart Beel',
  'Tom Wanerstrand',
  'Tom Wanerstrand; Brian LeBlanc',
  'Tom Wanerstrand; Jeff Holt',
  'Tom Wanerstrand; Jim Nelson',
  'Tom Wanerstrand; Ken Meyer, Jr.; Ron Spencer',
  'Tomas "zelgaris" Zahradnicek',
  'Tomas "zelgaris" Zahradnicek; Gines Quinonero',
  'Tony Harris',
  'Tony Shasteen',
  'Torstein Nordstrand',
  'Travis Ingram',
  'Trevor Claxton',
  'UDON',
  'Vatche Mavlian',
  'Veronica Jones',
  'Vince Locke',
  'Warren Mahy',
  'Will Simpson',
  'Will Simpson; Anson Maddocks',
  "William O'Connor",
  "William O'Connor; Greg Simanson",
  "William O'Connor; Heather Hudson",
  "William O'Connor; Julie Collins",
  "William O'Connor; Ken Meyer, Jr.",
  "William O'Connor; Leif Jones",
  "William O'Connor; Matt Cavotta",
  "William O'Connor; Michael Weaver",
  "William O'Connor; Sue Ann Harkey; Melissa Uran",
  'Zina Saunders',
  'Zina Saunders; Carmen Cornet',
  'Zina Saunders; Melissa Benson',
  'matrix von z',
  'rk post',
  'zelgaris',
];

export default artists;
