const cryptDefaults = {
  text: '',
  disciplines: {
    Abombwe: 0,
    Animalism: 0,
    Auspex: 0,
    Celerity: 0,
    Chimerstry: 0,
    Daimoinon: 0,
    Dementation: 0,
    Dominate: 0,
    Fortitude: 0,
    Melpominee: 0,
    Mytherceria: 0,
    Necromancy: 0,
    Obeah: 0,
    Obfuscate: 0,
    Obtenebration: 0,
    Potence: 0,
    Presence: 0,
    Protean: 0,
    Quietus: 0,
    Sanguinus: 0,
    Serpentis: 0,
    Spiritus: 0,
    Temporis: 0,
    Thanatosis: 0,
    Thaumaturgy: 0,
    Valeren: 0,
    Vicissitude: 0,
    Visceratika: 0,
  },
  virtues: {
    Defense: 0,
    Innocence: 0,
    Judgment: 0,
    Martyrdom: 0,
    Redemption: 0,
    Vengeance: 0,
    Vision: 0,
  },
  capacity: 'any',
  capacitymoreless: 'le',
  clan: 'any',
  sect: 'any',
  votes: 'any',
  titles: {
    primogen: false,
    prince: false,
    justicar: false,
    innercircle: false,
    baron: false,
    '1 votes': false,
    '2 votes': false,
    bishop: false,
    archbishop: false,
    priscus: false,
    cardinal: false,
    regent: false,
    magaji: false,
  },
  group: {
    1: false,
    2: false,
    3: false,
    4: false,
    5: false,
    6: false,
  },
  traits: {
    '1 intercept': false,
    '1 stealth': false,
    '1 bleed': false,
    '2 bleed': false,
    '1 strength': false,
    '1 strength': false,
    'additional strike': false,
    'optional maneuver': false,
    'optional press': false,
    prevent: false,
    aggravated: false,
    'enter combat': false,
    'black hand': false,
    seraph: false,
    infernal: false,
    'red list': false,
    flight: false,
  },
  set: 'any',
};

export default cryptDefaults;
