const defaultsLibraryForm = {
  text: '',
  type: 'any',
  discipline: 'any',
  blood: 'any',
  bloodmoreless: 'le',
  pool: 'any',
  poolmoreless: 'le',
  clan: 'any',
  sect: 'any',
  title: 'any',
  traits: {
    intercept: false,
    stealth: false,
    bleed: false,
    strength: false,
    dodge: false,
    'optional maneuver': false,
    'additional strike': false,
    aggravated: false,
    prevent: false,
    'optional press': false,
    'combat ends': false,
    'bounce bleed': false,
    'black hand': false,
    seraph: false,
    anarch: false,
    infernal: false,
  },
  set: 'any',
  setOptions: {
    'only in': false,
    'first print': false,
  },
  precon: 'any',
  preconOptions: {
    'only in': false,
    'first print': false,
  },
  artist: 'any',
};

export default defaultsLibraryForm;
