const precons = [
  ['any', 'ANY'],
  // ['bcp', 'ANY of BCP'],
  // ['20', 'V5', 'PM', 'Malkavian'],
  // ['20', 'V5', 'PN', 'Nosferatu'],
  // ['20', 'V5', 'PTo', 'Toreador'],
  // ['20', 'V5', 'PTr', 'Tremere'],
  // ['20', 'V5', 'PV', 'Ventrue'],
  ['19', 'SP', 'LB', 'Libertine Ball'],
  ['19', 'SP', 'PwN', 'Pact with Nephandi'],
  ['19', 'SP', 'DoF', 'Den of Fiends'],
  ['19', 'SP', 'PoS', 'Parliament of Shadows'],
  ['19', '25th', '', '25th Anniversary (Stanislava)'],
  ['18', 'FB', 'PM', 'Malkavian'],
  ['18', 'FB', 'PN', 'Nosferatu'],
  ['18', 'FB', 'PTo', 'Toreador'],
  ['18', 'FB', 'PTr', 'Tremere'],
  ['18', 'FB', 'PV', 'Ventrue'],
  ['18', 'Anthology', '', 'Anthology'],
  ['18', 'LK', '', 'Lost Kindred'],
  ['09', 'HttB', 'PKia', 'Lasombra / Kiasyd'],
  ['09', 'HttB', 'PSam', 'Nosferatu / Samedi'],
  ['09', 'HttB', 'PSal', 'Ventrue / Salubri antitribu'],
  ['09', 'HttB', 'PGar', 'Tremere / Gargoyle'],
  ['08', 'KoT', 'PB', 'Brujah'],
  ['08', 'KoT', 'PM', 'Malkavian'],
  ['08', 'KoT', 'PT', 'Toreador'],
  ['08', 'KoT', 'PV', 'Ventrue'],
  ['07', 'LotN', 'PA', 'Assamite'],
  ['07', 'LotN', 'PS', 'Follower of Set'],
  ['07', 'LotN', 'PG', 'Gionanni'],
  ['07', 'LotN', 'PR', 'Ravnos'],
  ['06', 'Third', 'PB', 'Brujah antitribu'],
  ['06', 'Third', 'PM', 'Malkavian antitribu'],
  ['06', 'Third', 'PTr', 'Tremere antitribu'],
  ['06', 'Third', 'PTz', 'Tzimisce'],
  ['05', 'LoB', 'PA', 'Akunanse'],
  ['05', 'LoB', 'PG', 'Guruhi'],
  ['05', 'LoB', 'PI', 'Ishtarri'],
  ['05', 'LoB', 'PO', 'Osebo'],
  ['05', 'KMW', 'PAl', 'Alastors'],
  ['05', 'KMW', 'PAn', 'Anathema'],
  ['05', 'KMW', 'PB', 'Baali'],
  ['05', 'KMW', 'PG', 'Gangrel antitribu'],
  ['04', 'Tenth', '', '10th Anniversary'],
  ['03', 'BH', 'PM', 'Malkavian antitribu'],
  ['03', 'BH', 'PN', 'Nosferatu antitribu'],
  ['03', 'BH', 'PTo', 'Toreador antitribu'],
  ['03', 'BH', 'PTr', 'Tremere antitribu'],
  ['03', 'Anarchs', 'PAB', 'Barons'],
  ['03', 'Anarchs', 'PAG', 'Gangs'],
  ['03', 'Anarchs', 'PG', 'Gangrel'],
  ['02', 'CE', 'PB', 'Brujah'],
  ['02', 'CE', 'PM', 'Malkavian'],
  ['02', 'CE', 'PN', 'Nosferatu'],
  ['02', 'CE', 'PTo', 'Toreador'],
  ['02', 'CE', 'PTr', 'Tremere'],
  ['02', 'CE', 'PV', 'Ventrue'],
  ['01', 'FN', 'PA', 'Assamite'],
  ['01', 'FN', 'PF', 'Follower of Set'],
  ['01', 'FN', 'PG', 'Giovanni'],
  ['01', 'FN', 'PR', 'Ravnos'],
  ['00', 'SW', 'PB', 'Brujah antitribu'],
  ['00', 'SW', 'PL', 'Lasombra'],
  ['00', 'SW', 'PT', 'Tzimisce'],
  ['00', 'SW', 'PV', 'Ventrue antitribu'],
]

export default precons;
