import { persist } from "valtio-persist";
import standardDecksData from "@/assets/data/standardDecks.json";
import {
  ADD_MODE,
  ALL,
  AUTO,
  CAPACITY_MIN_MAX,
  CRYPT_DECK_SORT,
  CRYPT_INVENTORY_SORT,
  CRYPT_SEARCH_SORT,
  DATE_NEW_OLD,
  DECKID,
  DECKS_ADV_SORT,
  EN,
  INVENTORY_CATEGORY,
  INVENTORY_MODE,
  LANG,
  LIBRARY_INVENTORY_SORT,
  LIBRARY_SEARCH_SORT,
  LIMITED_MODE,
  LIMITED_ONLY_DECKS,
  LIMITED_PRESET,
  NAME,
  PDA_SEARCH_SORT,
  PLAYTEST_MODE,
  QUANTITYx,
  RANDOM,
  RANK_HIGH_LOW,
  RECENT_DECKS,
  SEATING_CUSTOM_DECKS,
  SEATING_PLAYERS,
  SEATING_STANDARD_DECKS,
  SEATING_WITH_CUSTOM,
  SEATING_WITH_STANDARD,
  SHARED_KEY,
  SHOW_IMAGE,
  SHOW_LEGACY_IMAGE,
  STATE,
  TDA_SEARCH_SORT,
  THEME,
  TWD_SEARCH_SORT,
  TYPE,
} from "@/constants";

export const { store: settings } = await persist(
  {
    [SHOW_IMAGE]: true,
    [PLAYTEST_MODE]: false,
    [ADD_MODE]: false, // default to isDesktop
    [SHOW_LEGACY_IMAGE]: false,
    [INVENTORY_MODE]: false,
    [LIMITED_MODE]: false,
    [LIMITED_PRESET]: false,
    [LIMITED_ONLY_DECKS]: false,
    [SHARED_KEY]: false,
    [CRYPT_SEARCH_SORT]: CAPACITY_MIN_MAX,
    [CRYPT_DECK_SORT]: QUANTITYx,
    [LIBRARY_SEARCH_SORT]: TYPE,
    [CRYPT_INVENTORY_SORT]: NAME,
    [LIBRARY_INVENTORY_SORT]: NAME,
    [TWD_SEARCH_SORT]: DATE_NEW_OLD,
    [PDA_SEARCH_SORT]: DATE_NEW_OLD,
    [TDA_SEARCH_SORT]: RANK_HIGH_LOW,
    [DECKS_ADV_SORT]: NAME,
    [INVENTORY_CATEGORY]: ALL,
    [LANG]: EN,
    [THEME]: AUTO,
    [RECENT_DECKS]: [],
    [SEATING_WITH_CUSTOM]: true,
    [SEATING_WITH_STANDARD]: true,
    [SEATING_CUSTOM_DECKS]: [],
    [SEATING_STANDARD_DECKS]: Object.keys(standardDecksData)
      .toSorted((a, b) => standardDecksData[a].localeCompare(standardDecksData[b], "en"))
      .map((deckid) => ({
        [DECKID]: deckid,
        [NAME]: standardDecksData[deckid],
        [STATE]: true,
      })),
    [SEATING_PLAYERS]: [
      { [NAME]: "Player 1", [RANDOM]: false, [STATE]: true },
      { [NAME]: "Player 2", [RANDOM]: false, [STATE]: true },
      { [NAME]: "Player 3", [RANDOM]: false, [STATE]: true },
      { [NAME]: "Player 4", [RANDOM]: false, [STATE]: true },
      { [NAME]: "Player 5", [RANDOM]: false, [STATE]: true },
    ],
  },
  "settings",
);

export default settings;
